### ISSUE TITLE
avoid using cache when the image on the host have changed

### ISSUE THREAD

**Issue by benamizilber** [ligfx/k3d-registry-dockerd#2]
currently when I use locally built images, if I rebuild and restart a deployment that uses those images (and imagePullPolicy set to Always) I expect the newly built image to be used but the registry uses it's local cache and does not pull the new image from the host. I ma not sure if it's possible or how to do so but if the registry can comapre the sha256 of the cahched image with the one on the host, it can decide if the cache should be used or not. If checking the sha256 value is the same effort as pulling the image from the host, then I suggest to have an option to disable the registry local cache and allways pull from the host.

**Comment by ligfx** [comment]
Hey @benamizilber! I made an attempt to solve this in 26ed25c and pushed it to [ligfx/k3d-registry-dockerd:latest](https://hub.docker.com/r/ligfx/k3d-registry-dockerd/tags?page=1&name=latest). Can you try that out and let me know if it works for you?

**Comment by ligfx** [comment]
Released in v0.2, accessible on Docker Hub as [ligfx/k3d-registry-dockerd:v0.2](https://hub.docker.com/layers/ligfx/k3d-registry-dockerd/v0.2/images/sha256-c341c0c4246be92254a64b61d1d4413a929114afc9609a6417078dbb832185cc?context=repo)
