### ISSUE TITLE
Support for images with format _registry.k8s.io/ingress-nginx/controller@sha256:d5f8217feea..._

### ISSUE THREAD

**Issue by pvannierop** [ligfx/k3d-registry-dockerd#7]
Hi @ligfx,

I noticed that you have unreleased support for image specs that contain sha256 fingerprints. Would you mind releasing this so that I can use his?

Thanks again for this nice utility!

**Comment by ligfx** [comment]
@pvannierop done! Released as `ligfx/k3d-registry-dockerd:v0.6`

**Comment by pvannierop** [comment]
@ligfx Thanks! Much appreciated.
